/* This file is generated by scripts/generate-translation-registry.mjs. */
import type {SiteLocale} from "@/config/seo";
import type {LocaleTranslationFile} from "./translation-catalog";

import locale_ar from "./translations/ar.json";
import locale_ca from "./translations/ca.json";
import locale_cs from "./translations/cs.json";
import locale_da from "./translations/da.json";
import locale_de from "./translations/de.json";
import locale_el from "./translations/el.json";
import locale_es from "./translations/es.json";
import locale_fi from "./translations/fi.json";
import locale_fr from "./translations/fr.json";
import locale_he from "./translations/he.json";
import locale_hi from "./translations/hi.json";
import locale_hr from "./translations/hr.json";
import locale_hu from "./translations/hu.json";
import locale_id from "./translations/id.json";
import locale_it from "./translations/it.json";
import locale_ja from "./translations/ja.json";
import locale_ko from "./translations/ko.json";
import locale_ms from "./translations/ms.json";
import locale_nl from "./translations/nl.json";
import locale_no from "./translations/no.json";
import locale_pl from "./translations/pl.json";
import locale_pt_BR from "./translations/pt-BR.json";
import locale_ro from "./translations/ro.json";
import locale_ru from "./translations/ru.json";
import locale_sk from "./translations/sk.json";
import locale_sv from "./translations/sv.json";
import locale_th from "./translations/th.json";
import locale_tr from "./translations/tr.json";
import locale_uk from "./translations/uk.json";
import locale_vi from "./translations/vi.json";

export const GENERATED_TRANSLATION_FILES = {
  "ar": locale_ar,
  "ca": locale_ca,
  "cs": locale_cs,
  "da": locale_da,
  "de": locale_de,
  "el": locale_el,
  "es": locale_es,
  "fi": locale_fi,
  "fr": locale_fr,
  "he": locale_he,
  "hi": locale_hi,
  "hr": locale_hr,
  "hu": locale_hu,
  "id": locale_id,
  "it": locale_it,
  "ja": locale_ja,
  "ko": locale_ko,
  "ms": locale_ms,
  "nl": locale_nl,
  "no": locale_no,
  "pl": locale_pl,
  "pt-BR": locale_pt_BR,
  "ro": locale_ro,
  "ru": locale_ru,
  "sk": locale_sk,
  "sv": locale_sv,
  "th": locale_th,
  "tr": locale_tr,
  "uk": locale_uk,
  "vi": locale_vi,
} as unknown as Partial<Record<SiteLocale, LocaleTranslationFile>>;
